_wandb:
    value:
        cli_version: 0.21.0
        e:
            eg7ap09lveex66s9vh2von39ehg5vqj2:
                args:
                    - --node-ip-address=172.29.98.248
                    - --node-manager-port=41931
                    - --object-store-name=/tmp/ray/session_2025-07-21_21-17-32_355632_3549827/sockets/plasma_store
                    - --raylet-name=/tmp/ray/session_2025-07-21_21-17-32_355632_3549827/sockets/raylet
                    - --redis-address=None
                    - --metrics-agent-port=65528
                    - --runtime-env-agent-port=60342
                    - --logging-rotate-bytes=536870912
                    - --logging-rotate-backup-count=5
                    - --runtime-env-agent-port=60342
                    - --gcs-address=172.29.98.248:61713
                    - --session-name=session_2025-07-21_21-17-32_355632_3549827
                    - --temp-dir=/tmp/ray
                    - --webui=127.0.0.1:8265
                    - --cluster-id=cc7a7c0676f4bb874d33853ecb3ed416ef918eb949cacbe023c5f13b
                    - --startup-token=14
                    - --worker-launch-time-ms=1753125453352
                    - --node-id=ae1ff90ba58480fac2bb07583a10d0e862b0cd37bdec4f46aa20e954
                    - --runtime-env-hash=0
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1622224654336"
                        used: "1496789975040"
                email: kipbrio@gmail.com
                executable: /home/brian_bosho/miniconda3/bin/python
                git:
                    commit: e89285b522ee8a9d1bee592f41dd86d76741cd3e
                    remote: https://github.com/BrianBosho/FP.git
                gpu: NVIDIA L40-48Q
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51539607552"
                      name: NVIDIA L40-48Q
                      uuid: GPU-9111db93-1dd2-11b2-825e-3bd30d3a2412
                host: MobilityEdgeAI
                memory:
                    total: "67419688960"
                os: Linux-5.15.0-1077-aws-x86_64-with-glibc2.31
                program: /home/brian_bosho/miniconda3/lib/python3.12/site-packages/ray/_private/workers/default_worker.py
                python: CPython 3.12.2
                root: /home/brian_bosho/FP/FP/federated-gnn
                startedAt: "2025-07-21T19:17:57.438599Z"
                writerId: eg7ap09lveex66s9vh2von39ehg5vqj2
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 11
                - 30
                - 49
                - 77
            "2":
                - 1
                - 11
                - 30
                - 49
                - 77
            "3":
                - 13
                - 24
            "4": 3.12.2
            "5": 0.21.0
            "6": 4.46.3
            "12": 0.21.0
            "13": linux-x86_64
