# Citeseer Dataset Configuration
# Only dataset-specific settings - everything else inherited from base.yaml

datasets:
   - Computers
results_dir: results/computers
wandb_project: "FGL3-Computers"  # Dataset-specific wandb project

# Citeseer-specific experiment parameters
num_clients: [10]
num_rounds: 100
beta: [10, 10000, 1]
lr: 0.001
optimizer: Adam
data_loading: [chebyshev_diffusion, adjacency, full, zero_hop]
models: [GCN, GAT]
repetitions: 1

# nohup command to run the experiment
# nohup python -m src.experiments.run_experiments --config conf/computers_config.yaml > computers_config.out 2>&1 &