# ogbn-arxiv: adjacency + diffusion (no feature propagation)
# Propagation strategies that use graph structure but not full neighbourhood expansion.

datasets:
   - ogbn-arxiv
results_dir: experiments/results/ogbn-arxiv/adj_diff
wandb_project: "FGL4-Ogbn-Arxiv"

num_clients: [10]
num_rounds: 200
beta: [10000, 1]
hop: 2
save_results: true
use_wandb: true
wandb_entity: bosho
wandb_mode: online
data_loading: [adjacency, diffusion]
models: [GCN]
repetitions: 10
use_pe: false
use_unified_model: false

max_concurrent_clients: 10
client_num_gpus: 0.1
use_minibatch: true
batch_size: 1024
num_neighbors: [10, 10]
keep_data_on_gpu: false
early_stopping_patience: 20

model_architecture:
  GCN_arxiv:
    hidden_dim: 256
    num_layers: 3
    dropout: 0.5
    normalization: "batch"
  GAT_Arxiv:
    hidden_dim: 256
    num_layers: 3
    dropout: 0.5
    normalization: "batch"
    heads_hidden: 4
    heads_out: 6
    num_heads: 8

training:
  lr: 0.001
  optimizer: "Adam"
  weight_decay: 0.0005
  epochs: 3
  patience: 15

# nohup python -m src.fedgnn.experiments.run_experiments --config conf/ogbn-arxiv_config.yaml > arxiv_adj_diff.out 2>&1 &