# Pubmed Dataset Configuration
# Only dataset-specific settings - everything else inherited from base.yaml

datasets:
   - Pubmed
results_dir: results/pubmed
wandb_project: "FGL7-Pubmed"  # Dataset-specific wandb project

# Pubmed-specific experiment parameters
num_clients: [10]
num_rounds: 200
beta: [10,10000]
lr: 0.01
optimizer: Adam  # Pubmed works better with Adam
data_loading: [full, adjacency, zero_hop, diffusion]
models: [GCN, GAT]

hop: 2
use_pe: [True]
repetitions: 3

# nohup python -m src.experiments.run_experiments --config conf/pubmed_config_2hop.yaml > pubmed2_hop.out 2>&1 & 2193920