datasets: Citeseer
data_loading: full
models: GCN
num_clients: 1
num_rounds: 600
epochs: 3
optimizer: SGD
decay: 0.0005
beta: 
  - 1 
lr: 0.5
results_dir: results/centralized/citeseer
save_results: false
hop: 1
fulltraining_flag: false 
use_pe: 
  - false
pe_r: 64
pe_P: 16
normalize: qr