datasets: Cora
data_loading: full
models: GCN
num_clients: 5
num_rounds: 10
epochs: 3
optimizer: SGD
decay: 0.0005
beta: 2
lr: 0.5
results_dir: results/simple_test/cora_baseline
save_results: false
hop: 0
fulltraining_flag: false 
use_pe: false
pe_r: 64
pe_P: 16
normalize: qr