num_clients: 1
num_rounds: 600
epochs: 3
beta: 1
lr: 0.5
optimizer: SGD
decay: 0.0005
datasets:
  - Cora
data_loading:
  - full
models:
  - GCN
hidden_dim:
  - 16
results_dir: results/centralized/cora
save_results: true
hop: 1
fulltraining_flag: false 
use_pe: 
  - false
pe_r: 64
pe_P: 16
normalize: qr

