num_clients: 10
num_rounds: 20
epochs: 3
beta: 1
lr: 0.5
optimizer: SGD
decay: 0.0005
datasets:
  - Cora
data_loading:
  - full
  - zero_hop
  - adjacency
  - diffusion
models:
  - GAT
hidden_dim:
  - 16
results_dir: results/review/centralized/cora
save_results: true
hop: 1
fulltraining_flag: false 
use_pe: 
  - false
pe_r: 64
pe_P: 16
normalize: qr

# run python -m src.experiments.run_experiments --config conf/baseline/gcn_cora_baseline.yaml
