num_clients:
  - 1
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
  - 16
  - 18
  - 20

num_rounds: 100
epochs: 3
beta:
  - 10000
  - 1
lr: 0.5
datasets:
  - Cora
  - Citeseer
data_loading:
  - full
  - diffusion
  - adjacency
  - zero_hop
models:
  - GCN
results_dir: results/client_num_ablation_results
save_results: True
hop: 1
fulltraining_flag: false 
use_pe: True
pe_r: 64
pe_P: 16
normalize: qr