num_clients:
  - 10
num_rounds: 450
epochs: 3
beta:
  - 10000
  - 1
lr: 0.05
optimizer: Adam
decay: 0.0005
datasets:
   - Cora
data_loading:
  - zero_hop
  - adjacency
  - diffusion
  - full
models:
  - GAT
results_dir: results/gat/cora
save_results: true
hop: 1
fulltraining_flag: false 
use_pe:
  - false
  - true
pe_r: 64
pe_P: 16
normalize: qr

# python -m src.experiments.run_experiments --config conf/ablation/cora_gat.yaml