num_clients:
  - 10
num_rounds: 100
epochs: 3
beta:
  - 10000
lr: 0.1
optimizer: SGD
decay: 0.001
datasets:
   - Cora
data_loading:
  - adjacency
  - diffusion
  - full
models:
  - GCN
results_dir: results/cora_gcn_beta10000_no_pe_nzh
save_results: false
hop: 1
fulltraining_flag: false 
use_pe:
  - false
pe_r: 64
pe_P: 16
normalize: qr

# python -m src.experiments.run_experiments --config conf/ablation/cora_gcn_no_pe.yaml