num_clients:
  - 10
num_rounds: 450
epochs: 3
beta:
  - 10000
lr: 0.5
optimizer: SGD
decay: 0.0005
datasets:
   - Cora
data_loading:
  - full
  - zero_hop
  - adjacency
  - diffusion
models:
  - GAT
results_dir: results/review/gat/cora
save_results: True
hop: 2
fulltraining_flag: false 
use_pe:
  - True
pe_r: 32
pe_P: 16
normalize: qr
num_iterations: 60

# nohup python -m src.experiments.run_experiments --config conf/ablation/cora_gat.yaml