num_clients:
  - 10
num_rounds: 20
epochs: 3
beta:
  - 1
lr: 0.05
optimizer: Adam
decay: 0.0005
datasets:
   - Cora
data_loading: 
  - adjacency
models:
  - GAT
results_dir: results/review/gat/cora
save_results: false
hop: 1
fulltraining_flag: false 
use_pe:
  - true
pe_r: 64
pe_P: 16
normalize: qr
num_iterations: 20

# python -m src.experiments.run_experiments --config conf/ablation/cora_gat.yaml