num_clients:
  - 10
num_rounds: 300
epochs: 3
beta:
  - 1
  - 10000
lr: 0.5
datasets:
  - Cora
  - Citeseer
  - Pubmed
data_loading:
  - diffusion
  - adjacency
  - full
  - zero_hop
models:
  - GAT
results_dir: results/GAT_final/planetoid_300_rounds_pe
save_results: true
hop: 1
fulltraining_flag: false
use_pe: True
pe_r: 64
pe_P: 16
normalize: qr