num_clients:
  - 10
num_rounds: 10
epochs: 3
beta:
  - 1
lr: 0.01
optimizer: Adam
decay: 0.0005
datasets:
   - ogbn-arxiv
data_loading:
  - full
models:
  - GCN
results_dir: results/review/ablation/ogbn-arxiv
save_results: False
hop: 2
fulltraining_flag: false 
use_pe:
  - false
pe_r: 64
pe_P: 16
normalize: qr
num_iterations: 50

# nohup python -m src.experiments.run_experiments --config conf/ablation/ogbn-arxiv_config.yaml