num_clients:
  - 10
num_rounds: 300
epochs: 3
beta:
  - 1
  - 10
lr: 0.05
optimizer: Adam
decay: 0.0005
datasets:
   - Pubmed
data_loading:
  - zero_hop
  - adjacency
  - diffusion
  - full
models:
  - GCN
results_dir: results/pubmed_gcn_beta_10
save_results: true
hop: 1
fulltraining_flag: false 
use_pe: false
pe_r: 64
pe_P: 16
normalize: qr