num_clients:
  - 10
num_rounds: 450
epochs: 3
beta:
  - 1
  - 10
  - 10000
lr: 0.01
optimizer: Adam
decay: 0.0005
datasets:
   - Pubmed
data_loading:
  - zero_hop
  - adjacency
  - diffusion
  - full
models:
  - GCN
results_dir: results/pubmed_gcn_final
save_results: true
hop: 1
fulltraining_flag: false 
use_pe:
  - false
  - true
pe_r: 64
pe_P: 16
normalize: qr