beta: 1
data_loading:
- full
- adjacency
- zero_hop
datasets:
- Cora
- Citeseer
epochs: 3
fulltraining_flag: false
hop: 1
lr: 0.5
models:
- GCN
num_clients: 10
num_rounds: 10
results_dir: results/yaml_experiment_results
save_results: true
