num_clients: 3
num_rounds: 5
epochs: 2
beta: 0.8
lr: 0.3
datasets:
  - Cora
data_loading:
  - full
  - adjacency
models:
  - GCN
results_dir: results/extended_test_results
save_results: true
hop: 1
fulltraining_flag: false 