num_clients: 10
num_rounds: 100
epochs: 3
beta: 1
lr: 0.5
datasets:
  - Cora
data_loading:
  - full
  - adjacency
  - zero_hop
models:
  - GCN
results_dir: results/extended_test_results_cora
save_results: true
hop: 1
fulltraining_flag: false 